server:
  port: 8083

spring:
  application:
    name: service-passenger-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.98.247:3306/service-passenger-user?useUnicode=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456