server:
  port: 8081


spring:
  application:
    name: api-passenger
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 47.100.98.247
    port: 6379
    database: 0
    password: 123456